### ISSUE TITLE
Divide into Features

### ISSUE THREAD

**Issue by PokeyOne** [PokeyOne/pokey-logger#25]
Currently the library used serde and consequently a whole bunch of imports that may be undesirerable. It would be nice if the configuration and file stuff could be features that were disablable to prevent those imports.

Could even have a feature for macros too.

# To-Do
- [x] ~Time as a feature~ #26 
- [x] ~Config files as a feature~ #28 
- [x] ~Log files as a feature~ #26
